# Generated by Django 5.0.3 on 2024-11-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_filmeserie_delete_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmeserie',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to="media\x0cilmes_capas'"),
        ),
    ]
