# Generated by Django 5.0.3 on 2024-11-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_filmeserie_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmeserie',
            name='assistido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filmeserie',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='filmes_capas/'),
        ),
    ]
